### ISSUE TITLE
Map to the Oracle grammar

### ISSUE THREAD

**Issue by tschf** [bmazzarol/atom-plsql-linter#4]
In the readme, you mentioned you've implemented this to work when the extension is one of `sql` `pks` or `pkb`. 

There's a PL/SQL specific grammar for Atom that was just converted from the textmate bundle some time back. Maybe good to support your current implementation and additionally that grammar. (fwiw, the grammar package is [language-oracle](https://atom.io/packages/language-oracle)). I say both, as it can't hurt if someone doesn't have the grammar installed.

Here's a code snippet I've seen from another package to test the grammar (if it helps):

```cson
 module.exports = Blocky =
    activate: ->
      atom.workspace.observeTextEditors (editor) =>
        if editor.getGrammar().name in ["Ruby", "Ruby on Rails"]
```

..

I generally just use pkb,pks or sql my self, but there's a long list of file extensions that people have submitted into that grammar.

**Comment by bmazzarol** [comment]
The limitation might be on the COP side.

I have mapped it against the source.plsql.oracle grammar.

I was not sure how this was supposed to work, I followed a blog which gave me a shortcut to return the grammar for an open file, the grammar it returned for PL/SQL (Oracle) was that.

**Comment by tschf** [comment]
Oh yeah, cool! I didn't go inspecting to check how you'd done it :)
