### ISSUE TITLE
Install package-deps on activate

### ISSUE THREAD

**Issue by tschf** [bmazzarol/atom-plsql-linter#5]
In your package.json you have:

```json
"package-deps": [
    "linter"
  ]
```

Which relates to this project: https://github.com/steelbrain/package-deps

I think you are missing the step to actually install package dependencies.

The example on the README:

```js
module.exports = {
  activate() {
    // replace the example argument 'linter-ruby' with the name of this Atom package
    require('atom-package-deps').install('linter-ruby')
      .then(function() {
        console.log('All dependencies installed, good to go')
      })
  }
}
```

**Comment by bmazzarol** [comment]
Thanks, I will update the project. My approach to getting a package developed was to hack untill it worked. I appreciate your help in outlining areas to change and improve.
