### ISSUE TITLE
Add feedback when the server fails to start

### ISSUE THREAD

**Issue by tschf** [bmazzarol/atom-plsql-linter#6]
In the settings, you have that flag to start the program if it's not running on the specified port. You send a notification that it's starting, but no indication of failure. Might be handy, maybe monitor the exit code to see if it's non-zero.

For me, it was because I don't yet have the JDK installed (new system), which I realised after trying to launch it from the command prompt. 

```
C:\Users\trent\CustomPrograms\plsql-lint-server-1.0.1\bin>plsql-lint-server.bat 9876

A Java JDK is not installed or can't be found.

Please go to
  http://www.oracle.com/technetwork/java/javase/downloads/index.html
and download a valid Java JDK and install before running plsql-lint-server.

If you think this message is in error, please check
your environment variables to see if "java.exe" and "javac.exe" are
available via JAVA_HOME or PATH.
```

This is probably an edge case, but still..

**Comment by bmazzarol** [comment]
Totally valid I will do that. The error message might not be overly helpfull but no feedback is worse.
