### ISSUE TITLE
Windows lint warnings not coming through

### ISSUE THREAD

**Issue by tschf** [bmazzarol/atom-plsql-linter#8]
I'm testing on my work system. I follwed these steps

1. Start the plsql lint server from the command line:

```
C:\plsql-lint-server>bin\plsql-lint-server.bat 9999
[INFO] [07/16/2017 19:16:26.144] [default-akka.actor.default-dispatcher-3] [akka://default/user/iosystem-manager] All Workers reports ready, lets do this
[INFO] [07/16/2017 19:16:27.714] [default-server-dispatcher-9] [akka://default/user/server-plsql-lint-server] spinning up server
[INFO] [07/16/2017 19:16:27.745] [default-server-dispatcher-9] [akka://default/user/server-plsql-lint-server] name: Bound to port 9999
```

I have these settings

![image](https://user-images.githubusercontent.com/1747643/28252147-ae190cd2-6a5b-11e7-80f2-c6b2564cd9a9.png)

I have no `.oraclelint.json`.

Atom opens with a plsqlfile: test.sql - which should result in lint errors

```
begin

    khkh asd
end;
/
```

In the bottom right of Atom, there is a little icon that changes amber when I add more contents to the script, and then green which suggests the linter is processing

![image](https://user-images.githubusercontent.com/1747643/28252168-09fad54e-6a5c-11e7-9567-dbf2eeacbf98.png)

Any not 1 warning/error comes through.

Any clues?

Is there a way to start the server which will show requests coming through to see that's coming through properly. I thought it had this earlier?

---

edit: let us know if there's any other info I can provide?

**Comment by bmazzarol** [comment]
I will setup a windows env to test this on.

**Comment by bmazzarol** [comment]
Do you have version 1.0.2 of the plsql lint server running on your machine? 

If you run http://localhost:9876/version it will tell you.

**Comment by tschf** [comment]
Sorry for the delay. Confirming I'm on 1.0.2

**Comment by bmazzarol** [comment]
Sorry for the late response, finally got around to looking at this.

It is an issue with the lint server bmazzarol/plsql-lint-server#7.
